# Generated by Django 3.2.4 on 2021-07-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='create_date',
        ),
    ]
