# Generated by Django 3.2.4 on 2021-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(to='ads.Category'),
        ),
    ]
